### PR TITLE
Fix test event listener for nested and unlabeled tests

### LINKED ISSUE #1: Test output is missing `<COMPLETEDIN::>`
Test groups are not rendered correctly because `<COMPLETDIN::>` is missing.

Instead of 3 test groups, groups are nested:
image

See https://www.codewars.com/kumite/620a7361d746e5000f36a021

### PR DESCRIPTION
**Pull request by hobovsky**
Fixes #1 .

Supports:
 - Nested tests.
 - Tests without labels.

Example kumite: https://www.codewars.com/kumite/620a7361d746e5000f36a021/

Test output:

```text
<IT::>Top level test case

<FAILED::>not equal

<COMPLETEDIN::>

<DESCRIBE::>Test Odd

<IT::>Should return false for 1

<PASSED::>Test passed

<COMPLETEDIN::>

<IT::>Should return false for 7

<PASSED::>Test passed

<COMPLETEDIN::>

<COMPLETEDIN::>

<DESCRIBE::>Test even

<IT::>Should return true for 100

<PASSED::>Test passed

<COMPLETEDIN::>

<IT::>Should return true for 42

<PASSED::>Test passed

<COMPLETEDIN::>

<COMPLETEDIN::>

<DESCRIBE::>Test edge cases

<DESCRIBE::>Test zero

<IT::>Should return true for 0

<PASSED::>Test passed

<COMPLETEDIN::>

<COMPLETEDIN::>

<DESCRIBE::>Test -1

<IT::>Should return false for -1

<PASSED::>Test passed

<COMPLETEDIN::>

<COMPLETEDIN::>

<COMPLETEDIN::>

<DESCRIBE::>Unlabeled tests

<IT::>

<FAILED::>Incorrect answer for n=100<:LF:>not equal

<COMPLETEDIN::>

<IT::>

<FAILED::>Incorrect answer for n=100<:LF:>not equal

<COMPLETEDIN::>

<DESCRIBE::>

<IT::>

<FAILED::>Incorrect answer for n=100<:LF:>not equal

<COMPLETEDIN::>

<IT::>

<FAILED::>Incorrect answer for n=100<:LF:>not equal

<COMPLETEDIN::>

<COMPLETEDIN::>

<COMPLETEDIN::>
```

Current output panel:

image

Output panel with updated listener:

image

### CODE REVIEW

File: workspace/test.ml [hunk 1]
```diff
@@ -3,24 +3,51 @@ open OUnit
 let _esc_lf s =
   s |> Str.global_replace (Str.regexp_string "\n") "<:LF:>";;
 
-(* TODO Fix missing `<COMPLETEDIN::>` *)
+let cw_print_success = function
+  | _ -> print_endline ("\n<PASSED::>Test passed")
```
Comment (monadius) [inline workspace/test.ml]: `function` should only be used when there is a pattern-matching for the last argument. This function (and many other functions) should be written as
```ocaml
let cw_print_success () = print_endline "\n<PASSED::>Test passed"
```
Unnecessary parentheses should also be removed.

File: workspace/test.ml [hunk 2]
```diff
@@ -3,24 +3,51 @@ open OUnit
...
-    perform_test cw_print_test_event suite
+let rec dispatch_test_group = function
+  | label, TestList tests -> begin
+    print_endline("\n<DESCRIBE::>"^label);
+    run_tests tests;
+    print_endline("\n<COMPLETEDIN::>");
   end
-  | suite -> perform_test cw_print_test_event suite
+  
+and dispatch_test_case = function
```
Comment (monadius) [inline workspace/test.ml]: Don't create mutually recursive functions here (`and`).

File: workspace/test.ml [hunk 3]
```diff
@@ -3,24 +3,51 @@ open OUnit
...
+  | label, test_case -> begin
```
Comment (monadius) [inline workspace/test.ml]: Instead of pairs (`label, test_case`) it is better to use separate arguments: 
```ocaml
let dispatch_test_case label test_case =
```

**Comment by monadius** [comment]
Can I edit this PR somehow? Everything works fine but some small changes are required to make the code cleaner.

**Comment by hobovsky** [comment]
> Can I edit this PR somehow? Everything works fine but some small changes are required to make the code cleaner.

You can even steal the code to your repo.
Maybe I could make you contributor or something,  just don't know how.

File: workspace/test.ml (hunk 2 above)
Comment (hobovsky) [reply workspace/test.ml]: They are mutually recursive tho, did not get a good idea yet how to decouple them.

**Comment by hobovsky** [comment]
> Can I edit this PR somehow? Everything works fine but some small changes are required to make the code cleaner.

I made you a collaborator in my repo, but I  dont know if it helps anything :)

File: workspace/test.ml (hunk 2 above)
Comment (monadius) [reply workspace/test.ml]: Then everything is fine here. I missed `run_tests` in `dispatch_test_group`.

**Comment by monadius** [comment]
I will push my changes to your repository. Then you will be able to update this PR.

File: workspace/test.ml (hunk 3 above)
Comment (hobovsky) [reply workspace/test.ml]: Yeah, randomly spraying parentheses and semicolons is my way of dealing with syntax errors and type mismatches.

I am noob.

**Comment by kazk** [comment]
@monadius I gave you `Write` permission, so you should be able to push to this PR. Maintainers of upstream project can write to PRs unless the author opted out if I remember correctly.

File: workspace/test.ml (hunk 2 above)
Comment (hobovsky) [reply workspace/test.ml]: Btw this mutually recursive functions construct struck me as odd. I know some languages need it, but majority is fine with just some declaration and no special marker for recursive, or mutually recursive, functions.

Would you have any insight why ocaml, fsharp, maybe some other languages,  need it? Is it just syntax, or is it relevant from compilers point of view, or anything else?

Comment (monadius) [reply workspace/test.ml]: It is just syntax. The only real difference is that functions without `rec` (or `and`) can shadow functions (or constants) with the same name defined earlier and call old functions in their body. Compiling non-mutual recursive functions may be a little faster also.

**Comment by monadius** [comment]
I successfully pushed my changes to this PR.
